app/models/user.rb, config/application.rb, db/migrate/20200909085226_add_admin_to_users.rb, db/schema.rb, db/seeds.rb, lib/performance.rb, spec/factories/user_factory.rb, spec/models/user_spec.rb
#174164930 Add admin boolean to user model
Some rubocop fixes
=> #174164930 Add admin boolean to user model

app/controllers/auth0_controller.rb, app/controllers/dashboard_controller.rb, app/models/user.rb, app/views/dashboard/user.html.erb, app/views/layouts/application.html.erb, app/views/shared/_nav.erb, config/locales/en_GB.yml, config/routes.rb, spec/factories/user_factory.rb, spec/features/dashboard/admin_spec.rb, spec/features/dashboard/teams_spec.rb
Only enable team tab for group leads and admin tab for admins.
=> #174164944 Dashboard / Team / Admin tabs based on the user logged in

Gemfile, Gemfile.lock, app/presenters/dashboard_presenter.rb, config/initializers/reload_erb_changes.rb, config/locales/en_GB.yml, spec/presenters/dashboard_presenter_spec.rb
- Add empty notes to admin graph to fix JS error
- Rename to Murfin+
=> Fix admin graph

.rubocop.yml, app/controllers/application_controller.rb, app/presenters/nav_presenter.rb, app/views/layouts/application.html.erb, app/views/shared/_nav.erb
Show correct subnav e.g. new user should show 'Users' in subnav
=> Bw bug/subnav bug

app/views/admin/group_types/edit.html.erb, app/views/admin/group_types/index.html.erb, app/views/admin/user_groups/edit.html.erb, app/views/admin/user_groups/new.html.erb, app/views/admin/users/edit.html.erb, app/views/admin/users/index.html.erb, app/views/dashboard/individuals.html.erb
Some my-4, some my-5, let's standardize
=> Make top spacing the same everywhere

app/controllers/plans_controller.rb, app/javascript/helpers/bootstrap_select.js, app/models/activity.rb, app/services/schedule_builder.rb, app/services/schedule_parser.rb, app/views/plans/_activity_fields.html.erb, app/views/plans/edit.html.erb, config/locales/en_GB.yml, spec/factories/activity_factory.rb, spec/factories/plan_factory.rb, spec/features/plans/create_spec.rb, spec/features/plans/edit_spec.rb, spec/models/activity_spec.rb, spec/rails_helper.rb, spec/services/schedule_builder_spec.rb, spec/services/schedule_parser_spec.rb
- Add start_time and end_time serialization to activities
- Add to UI using time_select
=> Add start and end time to activities

Gemfile, Gemfile.lock, app/helpers/time_range_helper.rb, app/views/admin/time_ranges/index.html.erb, app/views/time_ranges/index.html.erb, config/locales/en_GB.yml, spec/features/teams/dashboard_spec.rb
=> Update TimeRange#value labelling

script/start_rails.sh, script/start_sidekiq.sh
- Remove redundant/slow `bundle check` from startup scripts
=> Speed up initial dev startup

app/controllers/admin/group_types_controller.rb, app/controllers/admin/time_ranges_controller.rb, app/controllers/admin/user_groups_controller.rb, app/controllers/admin/users_controller.rb, app/controllers/plans_controller.rb, app/controllers/time_ranges_controller.rb, config/locales/en_GB.yml, spec/features/admin/group_types/create_spec.rb, spec/features/admin/group_types/destroy_spec.rb, spec/features/admin/group_types/edit_spec.rb, spec/features/admin/time_ranges/create_spec.rb, spec/features/admin/time_ranges/destroy_spec.rb, spec/features/admin/time_ranges/edit_spec.rb, spec/features/admin/user_groups/create_spec.rb, spec/features/admin/user_groups/destroy_spec.rb, spec/features/admin/user_groups/edit_spec.rb, spec/features/admin/user_groups/set_lead_spec.rb, spec/features/admin/users/add_to_group_spec.rb, spec/features/admin/users/create_spec.rb, spec/features/admin/users/destroy_spec.rb, spec/features/admin/users/edit_spec.rb, spec/features/plans/create_spec.rb, spec/features/plans/destroy_spec.rb, spec/features/plans/edit_spec.rb, spec/features/time_ranges/create_spec.rb, spec/features/time_ranges/destroy_spec.rb, spec/features/time_ranges/edit_spec.rb
Still more tidying up to do but for starters now have a single set of notice translations.
=> #175365974 Merge duplicate translations in en_GB.yml

app/views/time_ranges/edit.html.erb
Time Range time to default to 9 am to 5 pm, rather than the current time.
=> Time Range default to 9am to 5pm

CHANGELOG.md, app/views/shared/_footer.erb, config/initializers/version.rb
=> Add versioning

app/views/admin/time_ranges/edit.html.erb, spec/features/admin/time_ranges/create_spec.rb
Time Range default to 9am to 5pm reinstated with a test this time as I accidentally removed in when sorting out the translations.
=> Time Range default to 9am to 5pm reinstated.

app/helpers/tag_type_helper.rb, app/javascript/helpers/bootstrap_helpers.js, app/javascript/stylesheets/forms.scss, app/models/activity.rb, app/models/tag_type.rb, app/views/plans/_activity_fields.html.erb, app/views/plans/_activity_tag_fields.html.erb, spec/rails_helper.rb
- Filter tags on activity form by selected parent tag
=> Filter Tags

CHANGELOG.md, app/controllers/time_ranges_controller.rb, app/views/shared/_nav.erb, app/views/time_ranges/edit.html.erb, app/views/time_ranges/index.html.erb, config/initializers/version.rb, spec/features/time_ranges/edit_spec.rb
Add Tag select to user time range form
Fix some TimeRange translations too
=> Tag select on user 'Actuals' form

CHANGELOG.md, app/models/concerns/activatable.rb, app/models/concerns/taggable.rb, app/views/admin/time_ranges/edit.html.erb, app/views/plans/_activity_fields.html.erb, app/views/plans/edit.html.erb, app/views/shared/_tag_association_fields.html.erb, app/views/shared/_tag_associations.html.erb, app/views/time_ranges/edit.html.erb, config/initializers/version.rb, spec/factories/tag_type_factory.rb, spec/features/plans/edit_spec.rb, spec/models/activity_spec.rb
- Show activities in table for usability
- Improve the way Taggable builds default tags
=> Add Activities Table

CHANGELOG.md, app/controllers/admin/users_controller.rb, app/models/plan.rb, app/models/signoff.rb, app/models/user.rb, config/initializers/version.rb, db/migrate/20201209103955_create_signoffs.rb, db/schema.rb, spec/factories/signoff_factory.rb, spec/models/plan_spec.rb, spec/models/signoff_spec.rb, spec/models/user_spec.rb
- Add signoffs backend, to store plan state.
=> #1 Add Signoffs

CHANGELOG.md, app/controllers/plans_controller.rb, app/models/activity.rb, app/views/plans/_activity_fields.html.erb, config/initializers/version.rb, config/locales/en_GB.yml, spec/features/plans/create_spec.rb
=> Show duration errors

CHANGELOG.md, Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/plans_controller.rb, app/controllers/signoffs_controller.rb, app/helpers/pundit_helper.rb, app/policies/activity_policy.rb, app/policies/application_policy.rb, app/policies/plan_policy.rb, app/policies/signoff_policy.rb, app/policies/time_range_policy.rb, app/views/plans/_activity_fields.html.erb, app/views/plans/_signoff_fields.erb, app/views/plans/edit.html.erb, app/views/plans/index.html.erb, app/views/shared/_tag_association_fields.html.erb, config/initializers/version.rb, config/locales/en_GB.yml, spec/features/plans/index_spec.rb, spec/rails_helper.rb, spec/requests/auth_spec.rb, spec/requests/notes_spec.rb, spec/requests/plans_spec.rb, spec/requests/signoffs_spec.rb, spec/support/feature_session_helpers.rb, spec/support/request_session_helpers.rb
- Add Pundit to PlanController
=> Authorize Plan

CHANGELOG.md, app/presenters/dashboard_presenter.rb, app/presenters/team_stats_presenter.rb, config/initializers/version.rb, spec/presenters/team_stats_presenter_spec.rb
- Fix issue with wrong values at end of line graph.
- Prevent server error when viewing graph with missing actuals.
=> Fix graph bugs

CHANGELOG.md, app/controllers/teams_controller.rb, app/helpers/graph_helper.rb, app/javascript/graphs/line_graph.js, app/javascript/helpers/bootstrap_helpers.js, app/presenters/dashboard_presenter.rb, app/presenters/team_stats_presenter.rb, app/views/teams/dashboard.html.erb, config/initializers/version.rb, config/locales/en_GB.yml, db/seeds.rb, spec/factories/tag_factory.rb, spec/presenters/dashboard_presenter_spec.rb, spec/presenters/team_stats_presenter_spec.rb
- Add tag filter to line graph
- Add random seed for tags
=> Add tag filter

db/seeds.rb
More realistic seed data with category and RiO tags on both planned and actual data.
=> #176572815 Tagged dummy data for production app

CHANGELOG.md, Gemfile, README.md, config/initializers/version.rb, script/generate_env_file.sh
Add a bash script to generate the initial .env file.
=> Add script to generate .env

README.md, config/application.rb, config/environments/development.rb
Think I must have switched this off while speeding up the SQL for the presenters.
=> Use Redis cache in dev

README.md
Other way won't work for redis
=> readme: update cache section.

CHANGELOG.md, app/controllers/teams_controller.rb, app/javascript/graphs/bar_chart.js, app/presenters/dashboard_presenter.rb, app/presenters/team_stats_presenter.rb, app/presenters/user_stats_presenter.rb, app/views/teams/_individuals_table.html.erb, app/views/teams/_table_filters.html.erb, app/views/teams/dashboard.html.erb, app/views/teams/individuals.html.erb, config/initializers/version.rb, config/locales/en_GB.yml, spec/features/teams/individuals_spec.rb, spec/presenters/dashboard_presenter_spec.rb, spec/presenters/team_stats_presenter_spec.rb, spec/presenters/user_stats_filter_tag_spec.rb
#176574699 Add Tag filter to Team Individuals Bar Chart
#176779588 Tag and Time Filter should also apply to Table on Team Individuals Page
=> Team Individuals Filter

app/models/plan.rb, spec/features/plans/edit_spec.rb
PR based on the other PR to avoid conflicts and give better view, rebase to master after merging the base one
=> job plans: fix bug which creates duplicated signoff.

spec/features/admin/team_individuals/data_spec.rb, spec/features/team_individuals/data_spec.rb, spec/features/users/data_spec.rb
Use Capybara’s find to wait until the element comes into view
=> #178195244 test fixes

app/views/plans/edit.html.haml
I have fixed this temporarily but we should build forms as tables, so it need more work.
=> UI bug/#178551971 job plan drop down bug
